### ISSUE TITLE
Accessing via iPad difficult to click on monster stands

### ISSUE THREAD

**Issue by carlpatten** [Lurkars/gloomhavensecretary#23] opened 2022-09-22 18:39 UTC
Issue: Under iPad/touchscreen the monster stand icons often highlight in red instead of opening the menu.

Steps to repeat:  
1. Open Gloomhaven Secretary for the first time with a fresh connection to the public server and an iPad.  Tested with both Safari and Chrome browsers.
2. Create a basic scenario with at least one monster.
3. Attempt to click on the monster stand icon to adjust hit points etc.  A red outline will appear around the stand icon instead of opening the menu.  Repeated clicking will eventually open the menu but may also resize the screen.
    
This issue was frequent enough that after an hour we gave up on using the app.

**Comment by Lurkars** [comment] 2022-09-23 05:49
There is a double click action on standees to mark them as active/inactive. Seems like it gets triggered by your touch events. I didn't notice this on my android touch device, but I will borrow an iPad from a friend to take a deeper look into the issue. Thanks for the report and sad, that the app didn't work for you as expected.

**Comment by Lurkars** [comment] 2022-09-23 17:45
Hopeyfully fixed with https://github.com/Lurkars/gloomhavensecretary/commit/8a8a55eb89fd647ea5d7f56118f455bdadfcf7fd. Would really appreciate, if you can test again with [0.17.4](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.17.4) and report here. Should already be deployed on [public server](https://ghs.champonthis.de).

If it is still not working, can you please open menu, go to settings and **disable** *Drag Initiative/HP/XP/Loot* and try again. I think issue is related to it. If it's not fixed now, but working with disabled *Drag*-option, at least I know where the issue is and can try to work on a proper fix (if not working already).

**Comment by carlpatten** [comment] 2022-09-23 20:22
Preliminary testing is positive; it is bringing up the menu every time when
I touch the standees.  I did not need to disable *Drag
Initiative/HP/XP/Loot *for it to work but it is good to know that option is
available.

Thank you for the fix!

**Comment by Lurkars** [comment] 2022-09-23 20:44
Thank you for the quick test and response.

**Closed** 2022-09-23 20:45 UTC
Labels: bug

**Comment by cerealcable** [comment] 2023-01-08 05:31
This issue seems to repeat now for me using latest. This is happening on Chrome via a touch device and on my Android phone via the PWA.

I haven't investigated this beyond finding this issue and seeing the red outline activate. We tested a mouse instead of touch and our problem went away on the laptop.

Seems we endlessly are enabling and disabling monsters with touch.

**Comment by Lurkars** [comment] 2023-01-08 06:15
Can someone confirm? I cannot reproduce. With solving this issue, I changed double click behaviour to long press for touch devices. So if you touch for more like 500ms it will toggle active, otherwise open menu. Can you try really snappy touches to verify the issue? I only have Android phone to test (with chrome and Firefox), both working fine for me.

**Comment by cerealcable** [comment] 2023-01-08 06:18
I've attempted rapid tapping on my phone and it seems to do the same. I'll try doing a screen capture.

**Comment by cerealcable** [comment] 2023-01-08 06:23
https://photos.app.goo.gl/9aexukidQuXMiiyC7

This is running as a PWA installed from Firefox on my Android phone. The same experience is happening on this Chromebook we are using.

**Comment by Lurkars** [comment] 2023-01-08 06:32
Can you confirm version in menu -> about? Just want to make sure, it's really latest version.

Maybe somehow "touchscreen detection" or so fail, I have no other clue by now. Also tagged now on different Android phone, full ending fine for me.

**Comment by cerealcable** [comment] 2023-01-08 06:39
Checked version, looks like the PWA hasn't been updating which is interesting, force update did help a lot. That cleared up the disabled problem with touch on my phone.

The Chromebook had the correct version and doesn't seem to disable the monsters but touching the monster often immediately dismisses the popup. I wonder if I should add some logging to these touch events so it's easier to understand.

I don't have a Chromebook either, I'll see about borrowing this one for testing.

A lovely other problem I noticed sometimes when I click a monster it immediately kills them. I believe this is a separate issue, though it can be seen in the screen I shared. Should I open an issue for this specifically? I wonder if it's kind of tied to those whole touch events problem discussed here.

**Comment by cerealcable** [comment] 2023-01-08 07:07
Created a new screen recording showing this problem.

https://photos.app.goo.gl/Qfq3GPGaymhjdx3Y7

**Comment by Lurkars** [comment] 2023-01-08 08:22
Really strange. Can you disable Drag in settings and re-test. The direct killing must be related to this.

Anyways, I put so much time already in this touch stuff and still not working fine. So I think I need to find a good library that knows better than me!

**Comment by Lurkars** [comment] 2023-01-08 08:27
I hope hammer.js is a way to go. I will try this out.

**Comment by cerealcable** [comment] 2023-01-08 08:44
I did previously have "Drag Initiative/HP/XP/Loot" disabled. It was quite tricky with a touch screen since scrolling would trigger so many unintentional changes.

I'm wondering if there is a conflict with events such as touch begin and end (begin being opening the modal, end closing it or pushing on the happen chance action beneath). Perhaps there could be a small change for touch ending, but it's something I intend to review later.

**Comment by Lurkars** [comment] 2023-01-08 09:52
I now migrated to Hammer.js, please checkout [v0.41.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.41.0) (should be deployed soon!)

**Comment by Lurkars** [comment] 2023-01-08 10:04
Needed to redeploy a fix. So please check out new hammer.js implementation with [v0.41.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.41.0)

**Comment by cerealcable** [comment] 2023-01-09 01:51
v0.41.0 definitely fixed our problems on both Android and the Chromebook! Thank you a ton @Lurkars for your effort here, I was definitely planning on investigating it today. We really enjoy using this in our gaming group!
