### ISSUE TITLE
Issue: curses are not removed from the monster attack deck 

### ISSUE THREAD

**Issue by rbeumer** [Lurkars/gloomhavensecretary#27] opened 2022-10-01 19:19 UTC
When the monsters have curses (10 in our case) the total number of curses in the monster attack deck does not decrease. You can see the number of curses when you tap on a monster card but the number of curses stays the same when a curse card is drawn by the monster.

Edit: we just reasoned that the app seems to track curses per monster species instead of for all monsters as one.

**Comment by Lurkars** [comment] 2022-10-02 05:51
I cannot reproduce the edit issue. Curses are tracked in the monster deck, which is same for all monsters. So cursing one entity, number of curses is shown same on every other monster.

The other issue is for now "works as designed" and is possible that I have just misunderstood GH rules: I only remove draw  curses when shuffling deck, so when 10 curses are added, you can only add a curse after shuffling. When curses are removed immediately after drawn, so that deck can always have up to 10 curses in upcoming cards, then we played this wrong in physical and I need to change.

**Comment by Lurkars** [comment] 2022-10-02 06:07
Okay, just reread the rules and cards should not be placed in discard and removed immediately. So I played it wrong and implemented it wrong. Will fix!

**Comment by Lurkars** [comment] 2022-10-02 07:24
Should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/454e39f6c557d4f0c6303b992144eb059a611b82 in [v0.18.4](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.18.4). Please test with latest version and report back. Thank you.

**Comment by rbeumer** [comment] 2022-10-02 09:01
Thanks, this is also fixed!

**Closed** 2022-10-02 09:01 UTC
Labels: bug
