### ISSUE TITLE
Graphics improvement suggestions

### ISSUE THREAD

**Issue by Infi220** [Lurkars/gloomhavensecretary#37] opened 2022-11-17 20:56 UTC
Excellent work with the app! I just have two UI suggestions:
1) Could you add that nice bright line to the center of the border glow around character tabs, similar to GHH app? In GHH it looked very nice and more vivid this way.
2) The contrast of icons was better in GHH because all icons were casting black shadow around them (you can see this when you zoom in the screenshot). Is it possible to add similar black shadow around icons in GHS? It would make them look sharper.

Here is a screenshot with a side by side view (device used: Pixel 4A)
![Screenshot (Nov 17, 2022 12_15_52) (2)](https://user-images.githubusercontent.com/34073985/202593970-d72ae6e4-b4ea-4648-8174-17fca4b520da.jpg)

**Comment by Lurkars** [comment] 2022-11-18 20:42
Hey thanks for the feedback.
I've added some small shadows now. As stated in the README:
> As I am not capable of good design/UX also feel free to contribute better assets.

So with the current state I am more than proud to reproduce a VERY similar look of the original helper. I am not allowed to use the original helper assets, so I had to create this on my own with mostly the Creator Pack and if I just look at the screen comparison, I can just simply say, that of course GHH looks better, but from what I am capable of GHS already looks fantastic. So yeah, all this fine nuances to improve are up to other's I think. If you find people to contribute better UI, I am more than happy about contributions. But UX/UI was always not my part, I am more a backend DEV and can do this whole project only, because I am of course a programmer. 

So this was a long answer, but I want to clarify why I only did some small changes and will close this issue anyways. I hope we may found some contributions on this topic for future!

**Closed by Lurkars** 2022-11-18 20:42 UTC

**Comment by Infi220** [comment] 2022-11-19 00:14
Thanks for the reply and detailed information. The problem with the hazy border is that on a small device like Pixel 4A the character tabs look quite blurry and blend with the background. If I may suggest one more small thing - could you add a small shadow around the character tabs (similar to what you did with the icons)? This would help the tabs stand out from the background.

**Comment by Lurkars** [comment] 2022-11-19 12:37
Okay, I tried to improve more, please take a look.

**Comment by Infi220** [comment] 2022-11-19 19:05
It looks better but now the background of the character mat is very dark. I actually have a lot of experience with graphics and I'd be happy to help with this asset. I found it as char-mat.png. Do you have the source of this image in the XCF or PSD format?

**Comment by Lurkars** [comment] 2022-11-19 21:04
I will increase some brightness. Besides, I don't have any more direct sources than the images in the repo. Most is based on the [Creator Pack](https://boardgamegeek.com/thread/1733586/files-creation). The `char-mat.png` is created from the `Character Class Mat/Character Class Mats - High HP_2P.png`.

**Comment by Infi220** [comment] 2022-11-19 22:32
This looks awesome, thank you so much! Too bad the source file in the creator pack is in such a low resolution. It would look sharper if we had higher quality source. Anyway, you've done tremendous work with this app. Thank you again!

If I design any improved assets later where should I post them? Is there any forum or Discord where people collaborate and share ideas on GHS, or is it mostly you alone working on this project? I noticed the discussion forum here is empty.

**Comment by Lurkars** [comment] 2022-11-19 23:02
This is only me. So best source for contribution would be GitHub for me. If you really want to create better assets, best would be to just fork this project, replace assets and create a PR for this. If all this git stuff is too technical for a designer, just ping me via mail, I have @catch-all, so something like assets@gloomhaven-secretary.de is fine.

**Comment by Lurkars** [comment] 2022-11-20 09:11
I created a discussion to this topic #40
